### ISSUE TITLE
Is there any limitations?

### ISSUE THREAD

**Issue by samuelcastro** [habx/apollo-multi-endpoint-link#55]
Hi, thanks for this library! Is there any limitation in regards to using it (support for subscriptions, cache or something else)?

Also it's not clear how headers should be set, don't you support a way of setting headers per endpoints? If we need to set headers in the `createHttpLink` function, does that mean that all headers are going to be sent to all endpoints? I have 2 different 3rd party services that uses `Authorization` as headers, therefore I can't send the same headers for all endpoints.

Thanks!

**Comment by jean9696** [comment]
Hi @samuelcastro, 

we support subscriptions and it's working for us. The only limitation we had is more about apollo cache itself: when 2 schemas have 2 differents entities with the sames `__typename`, apollo is merging them. To avoid this we added [namespaces](https://graphql-rules.com/rules/mutation-namespaces) in our schemas definitions & previxed our typenames (like h_project, i_project) so there is no conflict possible.

For your use-case with `Authorization`, you're right, setting headers in the `createHttpLink` function would add headers on each request. I don't want to add multiple HTTPLink since one is enough for http requests. 
I just made a [pull-request](https://github.com/habx/apollo-multi-endpoint-link/pull/56) so you can handle it in the next version.

And thank you for your pr btw !

**Comment by samuelcastro** [comment]
Hi @jean9696 thanks for the quick feedback, I'll take a look, thank you!

**Comment by jean9696** [comment]
I'm closing this issue since the problem has been fixed.
